name: Scribe Platforms CLI Action
description: Scan, collect and verifies evidence from Supply chain platforms.
author: Mikey Strauss
inputs:
  command:
    description: Command to run
    required: true
  valint_args:
    description: Valint args
  sign:
    description: Sign evidence
  platform:
    description: Select Platform
    required: true
  args:
    description: "Additional arguments to pass to Platforms"
  log-level:
    description: Log verbosity level {DEBUG,INFO,WARNING,ERROR,CRITICAL}
  log-file:
    description: Log file path
  config:
    description: Path to a configuration file
  print-config:
    description: Print the configuration after applying all other arguments and exit
  db-local-path:
    description: Local db path
runs:
  using: docker
  image: docker://scribesecurity/platforms:dev-latest
  args:
    - ${{ inputs.command }}
    - ${{ inputs.valint_args }}
    - ${{ inputs.sign && '--valint.sign' }}
    - ${{ inputs.command != 'discover' && '--valint.context-type=github' || '' }}
    - ${{ inputs.platform }}
    - ${{ inputs.args }} 
  

branding:
  icon: shield
  color: green
