name: Scribe Platforms CLI Action
description: Scan, collect and verifies evidence from Supply chain platforms.
author: Mikey Strauss
inputs:
  cmd:
    description: Command to run
    required: true
  log-level:
    description: Log verbosity level {DEBUG,INFO,WARNING,ERROR,CRITICAL}
  log-file:
    description: Log file path
  config:
    description: Path to a configuration file
  print-config:
    description: Print the configuration after applying all other arguments and exit
  db-local-path:
    description: Local db path
runs:
  using: docker
  image: docker://scribesecurity/platforms:dev-latest
  args:
    - ${{ fromJson(format('[{0}]', inputs.cmd)) }}
branding:
  icon: shield
  color: green
